M48
; DRILL file {KiCad (6.0.5-0)} date Saturday, 25 June 2022 at 14:04:22
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-25T14:04:22+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1102
%
G90
G05
T1
X3.5501Y-1.155
X6.575Y-1.155
T2
X3.5533Y-2.385
T0
M30
